name: Deploy to Selectel

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest # Определение окружения: используется последняя версия Ubuntu
        steps: # Шаги
            - name: Deploy using ssh # Название шага: Деплой с использованием SSH
              uses: appleboy/ssh-action@master # Использование готового действия для SSH-подключения
              with:
                  host: ${{ secrets.SELECTEL_HOST }} # Хост (сервер) для подключения, берется из секретов Github
                  username: ${{ secrets.USER_NAME }} # Имя пользователя для SSH, берется из секретов Github
                  key: ${{ secrets.SELECTEL_SSH_PRIVATE_KEY }} # Приватный ключ для SSH, берется из секретов Github
                  port: 22 # Порт для SSH-подключения (по умолчанию 22)
                  script: |
                      # Переход в директорию с проектом на сервере
                      cd ~/tg-bot-lebowski 
                      
                      # Вытягивание последних изменений из ветки main
                      git pull origin main 
                      git status # Проверка состояния git-репозитория

                      # Полная очистка Docker
                      docker rm -f $(docker ps -aq) 2>/dev/null || true
                      docker rmi -f $(docker images -aq) 2>/dev/null || true
                      docker builder prune -af
                      docker volume prune -f
                      docker network prune -f
                      docker system prune -af --volumes

                      # Сборка и запуск нового контейнера
                      docker build -t tg-bot-lebowski .
                            docker stop tg-bot-lebowski || true
                            docker rm tg-bot-lebowski || true
                            docker run -d \
                              --name tg-bot-lebowski \
                              -p 80:80 \
                              --env-file .env \
                              --restart=unless-stopped \
                              tg-bot-lebowski
