name: Deploy to Selectel

on:
  push:
    branches: [main]

env:
  SSH_HOST: ${{ secrets.SELECTEL_SSH_HOST }}
  SSH_USER: ${{ secrets.SELECTEL_SSH_USER }}
  SSH_PORT: ${{ 22 }}
  SSH_KEY: ${{ secrets.SELECTEL_SSH_PRIVATE_KEY }}
  DOCKER_IMAGE: tg-bot-lebowski

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Prepare .env from Secrets
      run: |
        echo "TG_BOT_TOKEN=${{ secrets.TG_BOT_TOKEN}}" > .env
        echo "TG_CHAT_ID=${{ secrets.TG_CHAT_ID}}" >> .env
        echo "TG_STICKER_FILE_ID=${{ secrets.TG_STICKER_FILE_ID}}" >> .env
        echo "1_DEBTOR=${{ secrets.DEBTOR_1}}" >> .env
        echo "2_DEBTOR=${{ secrets.DEBTOR_2}}" >> .env

    - name: Copy files to server
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ env.SSH_HOST }}
        port: ${{ env.SSH_PORT }}
        username: ${{ env.SSH_USER }}
        key: ${{ env.SSH_KEY }}
        source: ".env,Dockerfile,go.mod,cmd,README.md"
        target: "/home/${{ env.SSH_USER }}/tg-bot"

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ env.SSH_HOST }}
        port: ${{ env.SSH_PORT }}
        username: ${{ env.SSH_USER }}
        key: ${{ env.SSH_KEY }}
        script: |
          cd /home/${{ env.SSH_USER }}/tg-bot
          docker build -t $DOCKER_IMAGE .
          docker stop $DOCKER_IMAGE || true
          docker rm $DOCKER_IMAGE || true
          docker run -d \
            --name $DOCKER_IMAGE \
            -p 80:80 \
            --env-file .env \
            --restart=unless-stopped \
            $DOCKER_IMAGE